### ISSUE TITLE
Service will not start

### ISSUE THREAD

**Issue by stylerhall** [FrozenStormInteractive/Perforce-Synology#1]
Hello!

I installed Perforce-Synology (`HelixCoreServer-23.2-0035-x86_64-7.2.spk`) on my Synology `DS920+`, which worked great. _However_, I needed to update some settings and drives, which required removing and reinstalling the package. 

The re-installation succeeds, but upon completion, the service will not start. I've tried restarting the NAS but can't figure out how to get the package running again.

Any ideas on what I can try to get the package running? Thanks!

[EDIT]: I logged into the NAS via SSH to try to start the package from the command line. Here's the log output.

```
{"action":"prepare","error":{"code":0,"description":"failed to stop abnormal package, pkg=[HelixCoreServer] reason=[]"},"last_stage":"prepare_stop","stage":"stop","success":false}
```

**Comment by intelligide** [comment]
Do you get an error when you execute this command line: `sudo -u Perforce p4dctl-ng status --all` ?

(If it fails because it can't find the executable, try instead: `sudo -u Perforce /var/packages/HelixCoreServer/target/usr/local/bin/p4dctl-ng status --all`)

**Comment by stylerhall** [comment]
> Do you get an error when you execute this command line: `sudo -u Perforce p4dctl-ng status --all` ?

Yeah, this gave me the `sudo: p4dctl-ng: command not found`

> (If it fails because it can't find the executable, try instead: `sudo -u Perforce /var/packages/HelixCoreServer/target/usr/local/bin/p4dctl-ng status --all`)

This command returns `'dev-main' p4d service not running.`. This is from my original (initial) install, which I thought would have been removed when I uninstalled the package. Is it possible to nuke this from the system so I can re-start clean?

**Comment by intelligide** [comment]
First, try starting the service manually: `sudo -u Perforce p4dctl-ng start dev-main`

If there's an error, the service won't run, look in the folder `/var/packages/HelixCoreServer/tmp` (or `/volume1/@apptemp/HelixCoreServer`) for a file `p4d.dev-main.pid`. Delete it and try again to start the service manually.

If you have tried to change the volume where the perforce root is located, open the file `/var/packages/HelixCoreServer/etc/p4dctl-ng.conf.d/dev-main.conf` (or `/volume1/@appconf/HelixCoreServer/p4dctl-ng.conf.d/dev-main.conf`) with Vim and modify the environment variables `P4ROOT` (and `P4SSLDIR` if set) with the new volume.

Finally, if you want to nuke it, uninstall the package and delete the folders before reinstalling the package
- `/var/packages/HelixCoreServer`
- `/volume1/@appconf/HelixCoreServer`
- `/volume1/@appstore/HelixCoreServer`
- `/volume1/@apptemp/HelixCoreServer`
- `/volume1/@appdata/HelixCoreServer`
:warning: I've never tested this method, so I can't guarantee that it won't damage the NAS system. However, the chances of this happening are very low.
:warning: You will lose the management of the perforce root already created, you will have to create a new one.

**Comment by stylerhall** [comment]
> * I've never tested this method, so I can't guarantee that it won't damage the NAS system. However, the chances of this happening are very low.

I'll give it a shot, I'm _mildly_ worried about this, but we'll give it a shot. Will let you know how it goes!

**Comment by stylerhall** [comment]
I opted to nuke what was left around.

A few folders did not exist, but I nuked the ones that did. I rebooted the NAS, and all was good. I reinstalled the package, and it is now running again.

Thank you for the help!

**Comment by Cliffback** [comment]
> Finally, if you want to nuke it, uninstall the package and delete the folders before reinstalling the package
> 
> * `/var/packages/HelixCoreServer`
> * `/volume1/@appconf/HelixCoreServer`
> * `/volume1/@appstore/HelixCoreServer`
> * `/volume1/@apptemp/HelixCoreServer`
> * `/volume1/@appdata/HelixCoreServer`
>   ⚠️ I've never tested this method, so I can't guarantee that it won't damage the NAS system. However, the chances of this happening are very low.
>   ⚠️ You will lose the management of the perforce root already created, you will have to create a new one.

This also solved the same problem for me. Could run the perforce server manually with: `sudo -u Perforce /var/packages/HelixCoreServer/target/usr/local/bin/p4dctl-ng` but via the package manager it would fail.

Deleting everything here did the trick
